### ISSUE TITLE
Livestreams only feed

### ISSUE THREAD

**Issue by sn-o-w** [lzeke0/TwitchRSS#5]
It is possible? It would be nice to have a feed only for livestreams. Something like: https://twitchrss.appspot.com/liveonly/twitch

**Comment by lzeke0** [comment]
It is possible to get live streams appear as it appears now and I could filter everything else. However since streams are not really persistent so it does not really fit in the RSS concept. Because of this probably a lot of readers would have issues with it if I just filter events.

I might work on it later to make it semi-reasonable but it will need substantial effort.

**Comment by cristisilaghi** [comment]
Not really. RSS is a standardized, computer-readable format to access updates to online content. No matter if those updates are livestreams, news, vods or anything else. Knowing that my favorite streamer is livestreaming is a kind of update, IMHO.

And you already have the code to get the livestreams, you have to make a simplified feed, nothing else :)

Thank you in advance :D

**Comment by lzeke0** [comment]
The point I was trying to make is that twitch API does not provide a list of historic streams, only videos. For example if the streamer deletes the vod, there is no way [that I know] to get information on it after it is finished. So there is no way to get a reliable stream of items to make an RSS feed out of.

Technically I could store streams myself which is a half solution by itself but it's the best I can come up with. Also I need to review twitch API ToS because usually they don't allow to make separate databases out of API responses.

**Comment by jtagcat** [comment]
What about having the RSS feed link to TwitchRSS. After the stream with the same title (&/ duration?) turns in to a vod, link to that instead.

So, while the stream is live:
 - Title: Annoooooo
 - Link: https://twitchrss.appspot.com/livelink/linustech/1
(1 being the nth stream that we know of)
The link redirects (302) to http://www.twitch.tv/linustech
After the stream turns in to a vod, redirect (301) to https://www.twitch.tv/videos/623489158

If matching fails (though in theory, it shouldn't, title may change, but duration and the fact that the latest stream probably is the latest vod) for a vod that appears out of seemingly nowhere, push the vod (like you would get with /vod/), resulting in duplicate items.

![image](https://user-images.githubusercontent.com/38327267/82159426-7afdaa80-987d-11ea-9393-52ef061b2e03.png)
