### ISSUE TITLE
RSS Feed for a collection

### ISSUE THREAD

**Issue by timbroder** [lzeke0/TwitchRSS#9]
Is this possible with `TwitchRSS` as is? Thanks

**Comment by lzeke0** [comment]
What do you mean by collection? A group of channels?

**Comment by timbroder** [comment]
No a [collection of videos](https://www.twitch.tv/collections/pAWrUYWgNhUY1Q "collection of videos")

You can navigate the collection from the player

![image](https://user-images.githubusercontent.com/121503/44749732-685ba480-aae1-11e8-90bc-8f88b531b1de.png)

![image](https://user-images.githubusercontent.com/121503/44749746-73aed000-aae1-11e8-8119-23feed9fdbb9.png)

**Comment by lzeke0** [comment]
Got it.
It seems it is only supported on v5 API (now TwitchRSS is only on v3). Besides that I think it would be pretty easy to support collections once that's done.

**Comment by kristianserrano** [comment]
Using Inoreader, I curate an aggregated RSS feed that draws content from different sources related to a specific tabletop RPG. There are a lot of Twitch actual play streamers that play different TTRPGs, and I use this service for all of them. (Thank you!)

On several occasions, they've inquired about whether I can pull in feeds from a collection. Unfortunately, I cannot as of right now, but the demand is certainly there. Is this something that could be added sooner rather than later?

**Comment by wyattscarpenter** [comment]
It seems like with #20, we leapfrogged over v5 to Helix, and now API access to collections is no longer available, sad to say https://dev.twitch.tv/docs/api/migration#endpoint-equivalence

**Comment by lzeke0** [comment]
Not implementable sadly.
